# Our global, build settings
[build]
   base    = "."        # run the buold from this directory
   publish = "public"      # the output diretory to push to the CDN after the build
   command = "deploy site"  # the command to build our site
  
